### ISSUE TITLE
Compiler Explorer support

### ISSUE THREAD

**Issue by Tilka** [BiOpenly/Bi_Documentation#4]
It would probably speed up blackbox RE a lot to have OpenGL support in [Compiler Explorer](https://github.com/mattgodbolt/compiler-explorer). The shader binary can be retrieved using GL_ARB_get_program_binary's glShaderBinary(). Disassembly will just start out as a hexdump and gradually replace the parts we know about. This would also make it easy to contribute for people without access to ARM64 hardware.

**Comment by BiOpenly** [comment]
![image](http://i.imgur.com/n7MXtyl.png)

**Comment by BiOpenly** [comment]
Still needs some options to be able to be passed to it.
-vert, -fragment, -compute.
if vert or fragment then the other will need to be a no-op shader. I don't think the godbolt interface supports passing two files off to a compiler.
Compute would end up getting compiled by itself as expected.

**Comment by BiOpenly** [comment]
A hacked together compiler explorer is setup and running.
Got around the single file limitation by breaking up the input with a '<<<<<' token.
